services:
  naming-server:
    build: naming-server
    image: naming-server
    ports:
      - "8761:8761"
    networks:
      - subscription-network
  registration-postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=registration
      - POSTGRES_USER=registration
      - POSTGRES_DB=registration
    networks:
      - subscription-network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - subscription-network

networks:
  subscription-network: